### ISSUE TITLE
Rewrite It In Rust ™

### ISSUE THREAD

**Issue by janhohenheim** [squid-lang/abnf-validator#1]
Replace this repo as soon as https://github.com/SirRade/abnf-validator.rs is ready.

**Comment by Incyuna2z** [comment]
Hi Jan,

How could i run the code to verify ABNF grammar, or how to pass ABNF syntax ? Could you share a step to step instruction for windows 10?

Thanks,
Frank

**Comment by tautropfli** [comment]
Let's close this :)
