### ISSUE TITLE
How to run program ?

### ISSUE THREAD

**Issue by Incyuna2z** [squid-lang/abnf-validator#2]
Hi,

I didn't figure out how to run this program, how to pass ABNF syntax to this validator? Could you share a step to step instruction to me?

Thanks,
Frank

**Comment by tautropfli** [comment]
Hi Frank

The program accepts abnf input from STDIN.
Given that you are in the root of the repository and have built the validator using `make` you can run:

```
cat /path/to/syntax/file.abnf | ./abnf
```

**EDIT:** I have updated the [readme](https://github.com/squid-lang/abnf-validator/blob/master/readme.md) with instructions for building and running.
